import { useWriteContract, useReadContract } from 'wagmi';
import { parseEther } from 'viem';
// You'll need the ABI generated by Hardhat after compiling
import FutureLockABI from '../../../blockchain/artifacts/contracts/FutureLock.sol/FutureLock.json';

export const useFutureLock = () => {
  const { writeContract } = useWriteContract();

  const purchase = (id: number, price: string) => {
    writeContract({
      address: 'YOUR_CONTRACT_ADDRESS_HERE',
      abi: FutureLockABI.abi,
      functionName: 'purchaseInsight',
      args: [BigInt(id)],
      value: parseEther(price),
    });
  };

  return { purchase };
};