server:
  port: 8081
  netty:
    connection-timeout: 2s
    idle-timeout: 20s
  compression:
    enabled: true

spring:
  application:
    name: vault
  threads:
    virtual:
      enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/futurelock
    username: postgres
    password: margarine
    pool:
      initial-size: 100
      max-size: 5000
      max-idle-time: 30m
      validation-query: SELECT 1
  main:
    lazy-initialization: true

  resilience4j.circuitbreaker:
    instances:
      marketplaceService:
        registerHealthIndicator: true
        slidingWindowSize: 1000
        minimumNumberOfCalls: 500
        wait-duration: 5s
        failure-rate-threshold: 50

    silence4j.ratelimiter:
      instances:
        apiRatelimiter:
          limitForPeriod: 5000000
          limitRefreshPeriod: 1s
          timeoutDuration: 100ms

    management:
      endpoints:
        web:
          exposure:
            include: health,metrics
        health:
          show-details: ALWAYS

    mail:
      host: smtp.example.com
      port: 587
      username: ${MAIL_USERNAME}
      password: ${MAIL_PASSWORD}
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true